config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :goods
  resources :friends

  get 'items/new'
  get 'items/create'
  get 'items/edit'
  get 'items/update'
  get 'items/destroy'
  get 'items/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "items#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 get 'search', to:"goods#search" 
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
           has_many :goods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:brand, :price, :colour, :code, :quantity, :size)
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /goods or /goods.json
  def index
    @goods = Good.all
  end
def search
@goods =Good.where("brand LIKE ?", "%"+ params[:q] +"%")
end
  # GET /goods/1 or /goods/1.json
  def show

  end

  # GET /goods/new
  def new
    @good = current_user.goods.build
  end

  # GET /goods/1/edit
  def edit

  end

  # POST /goods or /goods.json
  def create

    @good = current_user.goods.build(friend_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to good_url(@good), notice: "Good was successfully created." }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1 or /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to good_url(@good), notice: "Good was successfully updated." }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1 or /goods/1.json
  def destroy
    @good.destroy!

    respond_to do |format|
      format.html { redirect_to goods_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def good_params
      params.require(:good).permit(:brand, :price, :colour, :code, :quantity, :size, :user_id)
    end
    def correct_user
      @good = current_user.goods.find_by(id: params[:id])
      redirect_to root_path, notice: "You are not friends with them!" if @good.nil?
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :colour, style: "display: block" %>
    <%= form.text_field :colour %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.number_field :code %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.number_field :size %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Brand:</strong>
    <%= friend.brand %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= friend.price %>
  </p>

  <p>
    <strong>Colour:</strong>
    <%= friend.colour %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= friend.code %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= friend.quantity %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= friend.size %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/goods/_form.html.erb
<%= form_with(model: good) do |form| %>
  <% if good.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
        <% good.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :brand, style: "display: block" %>
    <%= form.text_field :brand , class: "form-control form-control-lg", placeholder:"Brand"%>
  </div><br>

  <div class="field form-group">
    <% form.label :price, style: "display: block" %>
    <%= form.number_field :price, class: "form-control form-control-lg", placeholder:"Price" %>
  </div><br>

  <div class="field form-group">
    <% form.label :colour, style: "display: block" %>
    <%= form.text_field :colour, class: "form-control form-control-lg", placeholder:"Colour" %>
  </div><br>

  <div class="field form-group">
    <% form.label :code, style: "display: block" %>
    <%= form.number_field :code, class: "form-control form-control-lg",placeholder:"Code" %>
  </div><br>

  <div class="field form-group">
    <% form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class: "form-control form-control-lg", placeholder:"Quantity"%>
  </div><br>

  <div class="field form-group">
    <%form.label :size, style: "display: block" %>
    <%= form.number_field :size, class: "form-control form-control-lg", placeholder:"Size" %>
  </div><br>
  <div class="field form-group">
    <%form.label :size, style: "display: block" %>
    <%= form.number_field :user_id,id: :good_user_id, class: "form-control form-control-lg",value:current_user.id, type: :hidden %>
  </div><br>

  <div class="actions pt-2">
    <%= form.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/goods/_good.html.erb
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark" >
  <tr>
    <th>Brand</th>
    <th>Price</th>
    <th>Colour</th>
    <th>Code</th>
    <th>Quantity</th>
    <th>Size</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
<div id="<%= dom_id good %>">
  <tr>
<td>
  <%= good.brand %>
</td>



  <td>

    <%= good.price %>
  </td>

  <td>

    <%= good.colour %>
  </td>

  <td>
    <%= good.code %>
  </td>

  <td>
    <%= good.quantity %>
  </td>

  <td>
    <%= good.size %>
  </td>
  </tr>
</div>
  </tbody>

</table>
</div>

app/views/goods/edit.html.erb
<h1 class="theader">Editing items</h1>

<%= render "form", good: @good %>

<br>

<div>
  <%= link_to "Show this good", @good , class: "btn btn-primary"%> |
  <%= link_to "Back to goods", goods_path,  class: "btn btn-primary" %>
</div>

app/views/goods/index.html.erb
<h1 class="theader">Items</h1>
<br>
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark" >
<tr>
  <th>Brand</th>
  <th>Price</th>
  <th>Colour</th>
  <th>Code</th>
  <th>Quantity</th>
  <th>Size</th>
  <th colspan="3"></th>
</tr>
</thead>
  <tbody>
    <div id="goods">
      <% @goods.each do |good| %>
<% if good.user == current_user %>
      <tr>


      <td>
          <%= good.brand %>
      </td>

            <td>
        <%= good.price %>
            </td>
      <td>
        <%= good.colour %>
      </td>
          <td>
        <%= good.code %>
          </td>

          <td>
        <%= good.quantity %>
          </td>
          <td>
        <%= good.size %>
          </td>



        <td>
  <%= link_to "Show this item", good,  class: "btn btn-primary"%>



      <% end %>
        </td>
  </tr>
<% end%>

  </tbody>

</table>
</div>
<br>
  <%= link_to "New good", new_good_path, class: "btn btn-primary" %>

app/views/goods/new.html.erb
<h1 class="theader">New Items</h1>

<%= render "form", good: @good %>

<br>

<div>
  <%= link_to "Back to goods", goods_path,  class: "btn btn-primary" %>
</div>

app/views/goods/search.html.erb
<h1 class="theader">Search Result</h1>
<%= render @goods%>

app/views/goods/show.html.erb
<h1 class="theader">Item </h1>
<div class="table-responsive">
<table class="table table-striped table-bordered">
<thead class="thead-dark" >
<tr>
  <th>Brand</th>
  <th>Price</th>
  <th>Colour</th>
  <th>Code</th>
  <th>Quantity</th>
  <th>Size</th>
  <th colspan="3"></th>
</tr>
</thead>
<tbody>
  <div id="goods">


    <tr>


    <td>
        <%= @good.brand %>
    </td>

          <td>
      <%= @good.price %>
          </td>
    <td>
      <%= @good.colour %>
    </td>
        <td>
      <%= @good.code %>
        </td>

        <td>
      <%= @good.quantity %>
        </td>
        <td>
      <%= @good.size %>
        </td>
<td>
  <div>
    <%= link_to "Edit this good", edit_good_path(@good), class: "btn btn-primary" %> |
    <%= link_to "Back to goods", goods_path, class: "btn btn-primary" %>


  </div>

</td>



</tr>

  </div>
</tbody>

</table>
</div>
  <%= button_to "Destroy this good", @good, method: :delete , class: "btn btn-primary"%>

app/views/items/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: 	#D4AF37;">


  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag(  "Aracnotech Items (1).png", size: "50x50", :alt => "rss feed", :class => "img-circular") -%>
      </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
  <% if user_signed_in? %>
  <li class="nav-item">
    <%=link_to "Home", root_path, class:"nav-link active" %>
  </li>
        <li class="nav-item">
          <%=link_to "Item", goods_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%=link_to "Add", new_good_path, class:"nav-link active" %>
        </li>


        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
              <%= link_to "signout", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class:"nav-link" %>
        </li>
      <% else %>

      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>


      <% end %>

      </ul>
      <form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div class="home2">
<h1 class="theader"> Welcome to Aracnotech item manager</h1>
</div>

<div class="home">

      <%= image_tag(  "Aracnotech Items (1).png", size: "50x50", :alt => "rss feed", :class => "img-circular2") -%>

</div>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Item</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'items/header'%>

  <div class="container">

    <br/>
    <%if notice %>
    <%= render 'layouts/alerts'%>
    <% end %>
    
      <%= yield %>
  </div>

  </body>
</html>